on:
  push:
    branches: [main]
  pull_request:
name: CI
concurrency:
  group: release-${{ github.sha }}
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Flatpak Builder
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: hu.kramo.Hyperplane.Devel.flatpak
        manifest-path: hu.kramo.Hyperplane.Devel.json
        repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
        repository-name: gnome-nightly

